import type { Incident } from '../types/incident';

/**
 * Generate CSV string from incidents array
 */
export function generateCSV(incidents: Incident[]): string {
  const headers = [
    'ID', 'Type', 'Urgency', 'Status', 'Condition', 'Description',
    'Location', 'Lat', 'Lng', 'Reporter', 'People Affected',
    'Consciousness', 'Breathing', 'Bleeding', 'Hazards',
    'Created At', 'Dispatched At', 'Resolved At',
  ];

  const rows = incidents.map(inc => [
    inc.id,
    inc.type,
    inc.urgency || '',
    inc.status,
    inc.condition || '',
    inc.description || '',
    inc.location || '',
    inc.coordinates?.lat?.toString() || '',
    inc.coordinates?.lng?.toString() || '',
    inc.reporter || '',
    inc.people_affected?.toString() || '1',
    inc.consciousness === false ? 'No' : inc.consciousness === true ? 'Yes' : '',
    inc.breathing === false ? 'No' : inc.breathing === true ? 'Yes' : '',
    inc.bleeding ? 'Yes' : 'No',
    (inc.hazards || []).join('; '),
    inc.timestamp || '',
    inc.dispatched_at || '',
    inc.resolved_at || '',
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')),
  ].join('\n');

  return csvContent;
}

/**
 * Download a string as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export incidents as CSV
 */
export function exportCSV(incidents: Incident[]) {
  const csv = generateCSV(incidents);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(csv, `agapai-incidents-${timestamp}.csv`, 'text/csv;charset=utf-8;');
}

/**
 * Export incidents as JSON (for PDF generation or data exchange)
 */
export function exportJSON(incidents: Incident[]) {
  const json = JSON.stringify(incidents, null, 2);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(json, `agapai-incidents-${timestamp}.json`, 'application/json');
}

/**
 * Generate a simple HTML report that can be printed as PDF
 */
export function exportPrintableReport(incidents: Incident[]) {
  const timestamp = new Date().toLocaleString();
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>AgapAI Incident Report - ${timestamp}</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { font-size: 24px; margin-bottom: 8px; }
    h2 { font-size: 16px; margin-top: 24px; color: #555; }
    .meta { color: #888; font-size: 12px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f5f5f5; font-weight: 600; }
    .critical { color: #ef4444; font-weight: bold; }
    .high { color: #f97316; font-weight: bold; }
    .medium { color: #eab308; }
    .low { color: #22c55e; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>AgapAI Emergency Incident Report</h1>
  <p class="meta">Generated: ${timestamp} | Total Incidents: ${incidents.length}</p>
  <table>
    <thead>
      <tr>
        <th>ID</th><th>Type</th><th>Urgency</th><th>Status</th>
        <th>Condition</th><th>Location</th><th>Reporter</th><th>Created</th>
      </tr>
    </thead>
    <tbody>
      ${incidents.map(inc => `
        <tr>
          <td>${inc.id.slice(0, 8)}</td>
          <td>${inc.type}</td>
          <td class="${(inc.urgency || 'medium').toLowerCase()}">${(inc.urgency || 'medium').toUpperCase()}</td>
          <td>${inc.status}</td>
          <td>${inc.condition || ''}</td>
          <td>${inc.location || ''}</td>
          <td>${inc.reporter || ''}</td>
          <td>${inc.timestamp ? new Date(inc.timestamp).toLocaleDateString() : ''}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  <p class="meta" style="margin-top: 24px;">Report generated by AgapAI Emergency Dispatch System</p>
</body>
</html>`;

  const dateStr = new Date().toISOString().slice(0, 10);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  }
}
